replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

image:
  repository: 228997217230.dkr.ecr.us-east-1.amazonaws.com/ices/dotnetapp
  imagePullSecrets: aws
  pullPolicy: Always
  tag: "latest"

resources:
  requests:
    cpu: 100m
    memory: 512Mi

service:
  #type: ClusterIP
  type: NodePort
  port: 80
  targetPort: 8081

applicationPath: /weatherforecast
dnshost: path.api

istio:
  enabled: false
  ingressgateway: ingressgateway
  ingressPath: /path

prometheus:
  enabled: false
  name: prometheus
  namespace: namespace

nodeSelector: {}

tolerations: []

affinity: {}

properties:
  application.properties: |-
    server.servlet.context-path=/skyactivationcoreurl
    server.port=8080
    camunda.apiUrl = ${CAMUNDA_URL}