{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  gateways:
  - api-private-gateway
  hosts:
  - "{{ .Values.dnshost }}"
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.ingressPath }}
    name: {{ .Release.Name }}-routes
    rewrite:
      uri: {{ .Values.applicationPath }}
    route:
    - destination:
        host: {{ .Release.Name }}-service
        port:
          number: {{ .Values.service.port }}
{{- end }}
