{{- if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Values.prometheus.name }}
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }} 
  endpoints:
  - port: http
    path: {{ .Values.applicationPath}}/actuator/prometheus
    honorLabels: true
  selector:
    matchLabels:
      app: {{ .Release.Name }}
{{- end }}